<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/home.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
  <div id="home">
    <h1>Welcome to the Car Park Listing</h1>
    <h3>Recent Parks</h3>
    <park-list :parks="parks"> </park-list>
  </div>
</template>

<script>
import ParkList from "../components/ParkList";
export default {
  components: {
    ParkList,
  },
  data: () => ({
    parks: [],
  }),
  async mounted() {
    this.parks = await window.$.ajax(
      "/api/parks?limit=5&order_by=created_at"
    ).promise();
  },
};
</script>

<style>
</style>
