<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/home.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
  <div id="home">
    <p>Hello World</p>
    asdf
  </div>
</template>

<script>
// import store from '@/store'
export default {};
</script>

<style>
</style>
