<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/home.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
  <div id="home">
    <h1>Welcome to the Car Park Listing</h1>
    <user-parks v-if="auth"></user-parks>
    <h3>Recent Parks</h3>
    <park-list :parks="parks"> </park-list>
    <h3>Great Parks</h3>
    <park-list :parks="oldest_parks"> </park-list>
    <h3>Recommended Parks</h3>
    <park-list :parks="rec"> </park-list>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
import ParkList from "../components/ParkList";
import UserParks from "../components/UserParks";
export default {
  components: {
    ParkList,
    UserParks,
  },
  computed: {
    ...mapGetters({
      auth: "user/isAuth",
      user: "user/getAuth",
    }),
  },
  data: () => ({
    parks: [],
    oldest_parks: [],
    rec: [],
  }),
  async mounted() {
    //call on all the necessary park list with different ordering
    this.parks = await window.$.ajax(
      "/api/parks?limit=5&order_by=created_at"
    ).promise();
    this.oldest_parks = await window.$.ajax(
      "/api/parks?limit=5&order_by=created_at desc"
    ).promise();
    this.rec = await window.$.ajax(
      "/api/parks?limit=5&order_by=name desc"
    ).promise();
  },
};
</script>

<style>
</style>
